### PR TITLE
Add Jenkinsfile and pipeline template

### PR DESCRIPTION
**Pull request by csrwng**
Adds example pipeline, doc and template.

### CODE REVIEW

**Comment by csrwng** [comment]
@jorgemoralespou @bparees ptal

**Comment by bparees** [comment]
pretty much the same comments as on https://github.com/openshift-roadshow/parksmap-web/pull/4

**Comment by jorgemoralespou** [comment]
@csrwng same here

**Comment by csrwng** [comment]
\o/ :)

**Pull request merged**
